### ISSUE TITLE
Progress：The default background cannot be displayed in iOS

### ISSUE THREAD

**Issue by AlansaladA** [Telegram-Mini-Apps/TelegramUI#38]
The default background is made with ::after, but when I open the page on iOS, I find that ::after is not rendered, resulting in the loss of the default background.
 
![image](https://github.com/Telegram-Mini-Apps/TelegramUI/assets/21138159/706832b4-7836-4a71-93b8-fad7f346a7db)

**Comment by lapkoshka** [comment]
Same problem:

<img width="1283" alt="image" src="https://github.com/Telegram-Mini-Apps/TelegramUI/assets/4532214/c0c881b7-5625-4e44-a1e5-fcb8b2468fbf">

**Comment by mainsmirnov** [comment]
It is expected behavior. You can check out our figma for more insights [click](https://www.figma.com/community/file/1348989725141777736/telegram-mini-apps-ui-kit)

<img width="687" alt="Screenshot 2024-07-02 at 8 38 57 PM" src="https://github.com/Telegram-Mini-Apps/TelegramUI/assets/45998835/c9a943d9-ba12-4630-a0f9-6194e43fdcce">
